default_install_hook_types: [pre-commit]
repos:
-   repo: local
    hooks:
    -   id: ruff format
        name: ruff format
        entry: ruff format
        language: python
        types: [file, python]
    -   id: ruff lint
        name: ruff lint
        entry: ruff check
        language: python
        types: [file, python]
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [file, python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-json
        -   id: check-toml
        -   id: check-added-large-files
            args: [--maxkb=1024]
